# Generated by Django 4.1 on 2024-12-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_data_fotogradia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='data_fotogradia',
            new_name='data_fotografia',
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.CharField(max_length=150),
        ),
    ]
